version: '3'

services: 
  base: 
    image: mysql
    restart: always

    volumes:
      - "./.mysql-data/db:/var/lib/mysql"

    environment: 
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

    ports: 
      - '${FORWARD_DB_PORT:-3306}:3306'

